### ISSUE TITLE
rev_A: Clear description! 

### ISSUE THREAD

**Issue by KaitlinWan** [Zer0-M/d4#1]
### Q: Is it clear how you, a user, would interact with their data? How compelling is it? Does their interaction mechanism encourage you, the user, to continue exploring?

Yes! The image clearly displays how I, the USER, will be able to hover and explore the data. This data piques interests because it pertains to my life (health + cereal!). I think there is very limited options to explore. There's just a couple hover options and one chart.

**Comment by rlin6** [comment]
We will add more charts and include daily nutritional information
